### ISSUE TITLE
hello I would like to collaborate with your project by serving as a translator to Spanish. could translate any document with text

### ISSUE THREAD

**Issue by UlisesTJ** [contentful/migration-cli#71]

**Comment by thebiglabasky** [comment]
Hi,

By interpreting your message, I feel like there could be a misunderstanding with regards to contributions to such open source project.
Someone clarified this very well in this thread: https://github.com/cockroachdb/cockroach/issues/23038#issuecomment-368220870

We don't have any initiative to translate this project to spanish yet. If you want to engage and exchange with people from our Community, feel free to join us here: https://www.contentful.com/slack/

Thank you
