### ISSUE TITLE
changeEditorInterface is not a valid property name for a content type.

### ISSUE THREAD

**Issue by coffeepunk** [contentful/migration-cli#79]
When I run the following example migration

`contentful-migration --space-id SPACEID 16-change-editor-interface.js`

I get the this error

```
Errors in migration-cli-master/examples/16-change-editor-interface.js
Line 12: "changeEditorInterface" is not a valid property name for a content type.
10:     required: true
11:   });
12:   blogPost.changeEditorInterface('slug', 'slugEditor');
13: };
```

**Comment by zcei** [comment]
Hey @coffeepunk,

the new version of the Migration CLI hasn't been released yet, it's just merged to `master` 🙂
Did you use the codebase from this repository to run the example migration, or is `contentful-migration` the binary from NPM?

Best,
Stephan

**Comment by coffeepunk** [comment]
Hi @zcei I used the binary from the NPM package. I just ran the global install command this morning to get the latest from NPM.

**Comment by zcei** [comment]
Okay then this explains it. The example will only work once the new version is released that includes the code for `changeEditorInterface`.

It will probably be released in the upcoming week.

**Comment by coffeepunk** [comment]
Alright, I tried the master binary and then the example migration runs just fine. Looking forward the release.
