### ISSUE TITLE
Missing `Entry title` support for custom fields

### ISSUE THREAD

**Issue by stefanzmf** [contentful/migration-cli#85]
Let's take this basic migration:

```
module.exports = function (migration) {
  const person = migration.createContentType('person', {
    name: 'Person',
    description: 'A content type for a person'
  });

  person.createField('title', {
    name: 'Title',
    type: 'Symbol',
    required: true
  });

  person.createField('age', {
    name: 'Age',
    type: 'Number',
    required: true
  });
};
```

There is no way to mark a field as _Entry title_ which results in having all fields named _Untitled_. You can see the exactly behaviour http://sendvid.com/91p42rsz

**Comment by TimBeyer** [comment]
Hey Stefan,

what the web app calls title is exposed as `displayField` in the API.  
So you can set `person.displayField('title')` and it should show up correctly in the web app.

**Comment by stefanzmf** [comment]
Uh, makes sense. I was focused on ```createField``` docs looking for a flag or something. Closed
